CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    email   VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    date_created TIMESTAMP                               NOT NULL,
    requestor_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (request_id),
    CONSTRAINT fk_requestor_id FOREIGN KEY (requestor_id) REFERENCES users
);

CREATE TABLE IF NOT EXISTS items
(
    item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id    BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    request_id  BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (item_id),
    CONSTRAINT fk_item_user FOREIGN KEY (owner_id) REFERENCES users,
    CONSTRAINT fk_item_request FOREIGN KEY (request_id) REFERENCES requests
);

CREATE TABLE IF NOT EXISTS booking
(
    booking_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_start     TIMESTAMP                               NOT NULL,
    date_end       TIMESTAMP                               NOT NULL,
    booking_status VARCHAR(10),
    booker_id      BIGINT                                  NOT NULL,
    item_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (booking_id),
    CONSTRAINT fk_booking_user FOREIGN KEY (booker_id) REFERENCES users,
    CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text         varchar(500)                            NOT NULL,
    author_name  varchar(20)                             NOT NULL,
    item_id      BIGINT                                  NOT NULL,
    date_created TIMESTAMP                               NOT NULL,
    CONSTRAINT fk_comments_item FOREIGN KEY (item_id) REFERENCES items
);